### ISSUE TITLE
Crashes due to error from not finding id="description" read shelf

### ISSUE THREAD

**Issue by costa-rica** [YashTotale/goodreads-user-scraper#3]
**Describe the bug**
Scraping fails when a book description is not found. Some books do not have `<div id="description"`. This will cause the scrape_book method to return an error then crash the goodreads-user-scraper.

**To Reproduce**

1. run goodreads-user-scraper --user_id 149832357
2. once scraping gets to 'read' shelf it will crash on "Le Reveil" (this occurs on "Bounty In Brimstone" also)

error in terminal:
```
Traceback (most recent call last):
  File "/Users/nick/Documents/_environments/goodreads/bin/goodreads-user-scraper", line 33, in <module>
    sys.exit(load_entry_point('goodreads-user-scraper', 'console_scripts', 'goodreads-user-scraper')())
  File "/Users/nick/Documents/goodreads-user-scraper/scraper/__main__.py", line 28, in main
    scrape_user(args)
  File "/Users/nick/Documents/goodreads-user-scraper/scraper/__main__.py", line 10, in scrape_user
    shelves.get_all_shelves(args)
  File "/Users/nick/Documents/goodreads-user-scraper/scraper/shelves.py", line 131, in get_all_shelves
    get_shelf(args, shelf)
  File "/Users/nick/Documents/goodreads-user-scraper/scraper/shelves.py", line 95, in get_shelf
    book = books.scrape_book(book_id, args)
  File "/Users/nick/Documents/goodreads-user-scraper/scraper/books.py", line 109, in scrape_book
    "book_description": get_description(soup),
  File "/Users/nick/Documents/goodreads-user-scraper/scraper/books.py", line 85, in get_description
    book_description = soup.find("div", {"id": "description"}).findAll("span")[-1].text
AttributeError: 'NoneType' object has no attribute 'findAll'
```

**Expected behavior**
I think a good enough solution would be to return "No description found" for book description and continue scraping.

**Comment by costa-rica** [comment]
My proposed solution would be to replace (from inside scraper/books.py):

```py
def get_description(soup):
    return soup.find("div", {"id": "description"}).findAll("span")[-1].text
```
with

```py

def get_description(soup):
    if soup.find("div", {"id": "description"}) is None:
        return "No description found"
    else:
        return soup.find("div", {"id": "description"}).findAll("span")[-1].text
```

**Comment by YashTotale** [comment]
Fixed with https://github.com/YashTotale/goodreads-user-scraper/releases/tag/v1.2.1
