### ISSUE TITLE
Crashing when no cover image is found in book

### ISSUE THREAD

**Issue by costa-rica** [YashTotale/goodreads-user-scraper#4]
**Describe the bug**
Scraping fails when a book cover image is not found. Some books do not have `<img id="coverImage"`. This will cause the scrape_book method to return an error then crash the goodreads-user-scraper.

This happens with the test script. I have not encountered the problem in any of my own scrapings

**To Reproduce**

1. Clone the GitHub repository
`git clone https://github.com/YashTotale/goodreads-user-scraper.git`

2. Run the install script
`sh scripts/install.sh`

3. Run the test script
`sh scripts/test.sh`

error in terminal:
```
~/Documents/goodreads-user-scraper (main*) » sh scripts/test.sh                                                    130 ↵ nick@Nicks-Mac-mini
Scraping user...
👤 Scraped user

Scraping 'read' shelf...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/nick/Documents/goodreads-user-scraper/scraper/__main__.py", line 32, in <module>
    main()
  File "/Users/nick/Documents/goodreads-user-scraper/scraper/__main__.py", line 28, in main
    scrape_user(args)
  File "/Users/nick/Documents/goodreads-user-scraper/scraper/__main__.py", line 10, in scrape_user
    shelves.get_all_shelves(args)
  File "/Users/nick/Documents/goodreads-user-scraper/scraper/shelves.py", line 131, in get_all_shelves
    get_shelf(args, shelf)
  File "/Users/nick/Documents/goodreads-user-scraper/scraper/shelves.py", line 95, in get_shelf
    book = books.scrape_book(book_id, args)
  File "/Users/nick/Documents/goodreads-user-scraper/scraper/books.py", line 111, in scrape_book
    "book_image": soup.find("img", {"id": "coverImage"}).attrs.get("src"),
AttributeError: 'NoneType' object has no attribute 'attrs'
```

**Expected behavior**
I think a good enough solution would be to return "No image found" for book cover image and continue scraping.

**Comment by YashTotale** [comment]
Not an issue anymore as books automatically have a placeholder image (ex. https://www.goodreads.com/book/show/15208845-proceedings-of-the-first-results-workshop-on-eurostarrs-wise-losac-cam)
